### ISSUE TITLE
Remember closed tabs

### ISSUE THREAD

**Issue by jomo** [rugk/how-did-i-get-here#1]
Would be nice if the extension would remember the URLs of the opener tab when a tab is opened. That way it can be opened again when the opening tab has been closed.

Also helpful in case the opener tab has navigated to a different site, so the tab is no longer useful as a context

**Comment by rugk** [comment]
So this would require saving all the tabs you have opened and their history? Hmm…
We could also only save data when the tab is actually closed.

The second thing might be something different, but indeed related. Only saving data on close, would not help here… 
I'll have a look at if/how this can be done.

**Comment by jomo** [comment]
Only requires saving one URL for each currently open tab.

**Comment by rugk** [comment]
Hmm… to solve the second problem that's not enough:

I can e.g. 
* open newtab website1 -> click link in new tab to website2 (the easy case)
* open newtab website1, naigate to website2 -> click link in new tab to website3 (the easy case); navigate in first tab to website4 (now the history is still incomplete/wrong when we only save website1 for tab1)

**Comment by jomo** [comment]
case two:

0. tab1 = site1 (origin = null)
0. tab1 = site2
0. tab2 = site3 (origin = site2)
0. tab1 = site4

We'd save tab2's origin as site2, which is correct.
For tab1, we don't save anything because you navigated there from within tab1 and that can be accessed via the back button.

**Comment by rugk** [comment]
Oh, yeah, looks as if it is possible this way. But enough theory, I need to try that out (later) to see how it actually works. :wink:

**Comment by rugk** [comment]
BTW @jomo feel free to test out the current master. Some minor stuff still needs to be tweaked, but basically it should already work.

**Comment by pkrabbit** [comment]
@rugk Haha I was going to suggest just that feature!

I've tested the master and it works for me.

I have a small suggestion, can the link be clickable even after the original tab is closed? It could then simply open the link in a new tab.

Thank you for this extension!

**Comment by rugk** [comment]
> I have a small suggestion, can the link be clickable even after the original tab is closed? It could then simply open the link in a new tab.

Nice idea, maybe open a new issue for that. :smile: 

Though I have to say maybe a user would expect it to restore the exact same tab as before (which we actually could, up to 10 entries or so in the past), but we cannot assure it always works.
