### ISSUE TITLE
Highlight or open tabs on click of title

### ISSUE THREAD

**Issue by rugk** [rugk/how-did-i-get-here#2]
It seems we cannot switch to tabs when they are clicked upon in the popup, but at least we can highlight them: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/highlight

**Comment by jomo** [comment]
Should be possible using [windows.update](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/update) and [tabs.update](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/update) to set the window/tab to active.

**Comment by rugk** [comment]
Uh yeah you got it. Thought there would be a better method for it but yes, mostly `tabs.update()` seems to be fine.

Now, one just has to decide whether highlight or directly opening tab would be better…

**Comment by rugk** [comment]
BTW highlighting tabs is not even supported by Firefox right now, so I've [opened a bug for this](https://bugzilla.mozilla.org/show_bug.cgi?id=1464601).
